### ISSUE TITLE
Trying to get a plugin started.

### ISSUE THREAD

**Issue by steviss** [Mayron/LibMayronObjects#1]
Hey man,

Great job on the library. I am liking what I am seeing, only If I could get the project started that would be great.

I am trying to build an addon for my guild. I had a small addon back in the day, when retail was a big thing (around WOTLK). But since I have fallen out of favor with Lua. I mostly dabble in TypeScript and C# now.

I am trying to get an addon setup. But I am getting errors.

I can't seem to import LibMayronObjects and LibMayronDB.

I changed the Interface Version in both .toc files (as you said in your guides) to 11304 (thats what I get by running /run print((select(4, GetBuildInfo()))); in WoW Classic).

But I am getting the following error from WoW Classic:

```
Message: Interface\AddOns\HarmonyAntiDC\Library\LibMayronDB\LibMayronDB.toc(1): error: not well-formed (invalid token)
Time: Thu Apr  2 18:14:35 2020
Count: 3
```

and

```
Message: (null)
Time: Thu Apr  2 18:14:35 2020
Count: 3
```

I tried to use one of your "test" classes in my plugin .lua. But as I said I get the error up top.

Any way you can help me get everything setup so I can try out the framework?

My plugintest.toc:

```

##Interface: 11304
##Title: plugintest
##Author: steviss
##Notes: Test addon.
##Version: 1.0

plugintest.lua

#Myron Objects
Library\LibMayronObjects\LibMayronObjects.lua
Library\LibMayronObjects\LibMayronObjects.xml
Library\LibMayronObjects\LibStub.lua
Library\LibMayronObjects\Attributes\InCombatAttribute.lua
Library\LibMayronObjects\Objects\FrameWrapper.lua
Library\LibMayronObjects\Objects\LinkedList.lua
Library\LibMayronObjects\Objects\List.lua
Library\LibMayronObjects\Objects\Map.lua
Library\LibMayronObjects\Objects\Stack.lua

# Myron DB
Library\LibMayronDB\LibMayronDB.lua
Library\LibMayronDB\LibMayronDB.toc
Library\LibMayronDB\LibMayronObjects.lua
Library\LibMayronDB\LibStub.lua

```

My plugintest.lua file:
```

-- luacheck: ignore self 143 631
local lib = _G.LibStub:GetLibrary("LibMayronObjects");

local function HelloWorld_Test1() -- luacheck: ignore
    print("HelloWorld_Test1 Started");

    local TestPackage = lib:CreatePackage("HelloWorld_Test1", "Test");

    local HelloWorld = TestPackage:CreateClass("HelloWorld");

    function HelloWorld:Print(private, msg)
        assert(msg == "My 2nd Message");
        assert(private.secret == "This is a secret!");
    end

    function HelloWorld:__Construct(private, msg)
        private.secret = "This is a secret!";
        assert(msg == "My 1st Message");
        assert(self ~= HelloWorld);
    end

    function HelloWorld:__Destruct()
        --print("Instance Destroyed"); -- works!
    end

    local instance = HelloWorld("My 1st Message");
    instance:Print("My 2nd Message");

    local HelloWorld2 = lib:Import("Test.HelloWorld_Test1.HelloWorld");
    assert(HelloWorld == HelloWorld2);

    local className = instance:GetObjectType();
    assert(className == "HelloWorld", className);

    instance:Destroy();

    print("HelloWorld_Test1 Successful!");
end

```

- Just to add that the Libraries are in the folders I put in the path.

If you can help me get started that would be great.

**Comment by jadissa** [comment]
if anyone can fix it, it'll be that super cute and super smart guy Mayron 😍

**Comment by Michael-Richards-UoM** [comment]
@steviss @jadissa Hey all, sorry for missing this. I didn't think people were using the library and so I haven't been great at tracking these issues. 

I need to find a better way of alerting me on these things. I've mostly been using TypeScript and C# these days for work too :)

I bet this isn't the issue but usually you have a space after the 2 `##` symbols.
Usually, when you use a `.toc` file, you need it at the root of your addon's folder. So you can either use another `.toc` file for another addon and include LibMayronObjects as part of that, use an XML file to load it, or you can make the LibMayronObjects as a standalone AddOn and have the LibMayronObjects folder in the interface>AddOns folder and have the .toc file in there. I think the issue is relating to the structure because of how you specify `Library\LibMayronObjects\LibMayronObjects.lua` for example.

There is an XML file to load all the related files, so in the `.toc` file I only specify:

```toc
LibStub.lua
LibMayronObjects.xml
```

So the XML loads them all. If you are not using LibMayronObjects as a standalone addon then you would usually copy the libraries folder into some sort of "Libs" folder in your addon and specify the `xml` (and completely ignore the LibMayronObjects.toc file) in your own addons `.toc` file.

If you want more help in a more collaborative way then I would be willing to chat with you on my discord server too: https://discordapp.com/invite/8Kh3maU

**Comment by Mayron** [comment]
@steviss @jadissa Hey all, sorry for missing this. I didn't think people were using the library and so I haven't been great at tracking these issues. 

I need to find a better way of alerting me on these things. I've mostly been using TypeScript and C# these days for work too :)

I bet this isn't the issue but usually you have a space after the 2 `##` symbols.
Usually, when you use a `.toc` file, you need it at the root of your addon's folder. So you can either use another `.toc` file for another addon and include LibMayronObjects as part of that, use an XML file to load it, or you can make the LibMayronObjects as a standalone AddOn and have the LibMayronObjects folder in the interface>AddOns folder and have the .toc file in there. I think the issue is relating to the structure because of how you specify `Library\LibMayronObjects\LibMayronObjects.lua` for example.

There is an XML file to load all the related files, so in the `.toc` file I only specify:

```toc
LibStub.lua
LibMayronObjects.xml
```

So the XML loads them all. If you are not using LibMayronObjects as a standalone addon then you would usually copy the libraries folder into some sort of "Libs" folder in your addon and specify the `xml` (and completely ignore the LibMayronObjects.toc file) in your own addons `.toc` file.

If you want more help in a more collaborative way then I would be willing to chat with you on my discord server too: https://discordapp.com/invite/8Kh3maU
